### ISSUE TITLE
BOM upload failed

### ISSUE THREAD

**Issue by chamlyidunil** [mkep-dev/dependency-track-bom-publish-gradle#1]
I tried upload bom.xml to dependency track server and it gets failed. 
messages:
HTTP request failed. See error message:
 http: nodename nor servname provided, or not known.

my configurations:

dtrackPublishBom{
    host "http://localhost:8081"
    apiKey "ddGoq9pjLQqR6YZjNh1mcc24IALZxx"
    projectUuid "fc7b4602-e2dd-4823-b36a-e64080d68880"
    realm "/api/v1/bom"
    bomFile file("build/reports/bom.xml")
}
publishBom.dependsOn(cyclonedxBom)

it saying node or servername not provided

**Comment by mkep-dev** [comment]
Sorry for the delay
I will check it today. 
Or could you fix it?

**Comment by mkep-dev** [comment]
is there a reason why you use the 'https' protocol?

EDIT:
Okay that's not an bug in the classic way -> simply drop the 'https' at the beginning of your host field


Nevertheless, I will fix that for a better usability.

**Comment by chamlyidunil** [comment]
I could be able to fix that. i go through your code and find out the pattern, how it should configured. 
i update it as     -  host "10.16.32.84:8081"
thianks

**Comment by chamlyidunil** [comment]
We have another requirement, create BOM file from collection of jars
do you have any solution or suggestion for that.

**Comment by mkep-dev** [comment]
Unfortunately I have no suggestion what could help you

Thanks for your response.
